load(":image_opts.bzl", "boot_image_opts")
load(":msm_kernel_le.bzl", "define_msm_le")
load(":target_variants.bzl", "le_variants")

target_name = "qcs610"

def define_qcs610():
    _qcs610_in_tree_modules = [
        # keep sorted
        "arch/arm64/geniezone/gzvm.ko",
        "drivers/base/regmap/regmap-kunit.ko",
        "drivers/base/regmap/regmap-ram.ko",
        "drivers/base/regmap/regmap-raw-ram.ko",
        "drivers/block/virtio_blk.ko",
        "drivers/block/zram/zram.ko",
        "drivers/bluetooth/btbcm.ko",
        "drivers/bluetooth/btqca.ko",
        "drivers/bluetooth/btsdio.ko",
        "drivers/bluetooth/hci_uart.ko",
        "drivers/char/hw_random/cctrng.ko",
        "drivers/char/rdbg.ko",
        "drivers/char/virtio_console.ko",
        "drivers/clk/clk-gate_test.ko",
        "drivers/clk/clk_test.ko",
        "drivers/clk/qcom/camcc-sm6150.ko",
        "drivers/clk/qcom/clk-dummy.ko",
        "drivers/clk/qcom/clk-qcom.ko",
        "drivers/clk/qcom/clk-rpmh.ko",
        "drivers/clk/qcom/debugcc-sm6150.ko",
        "drivers/clk/qcom/dispcc-sm6150.ko",
        "drivers/clk/qcom/gcc-sm6150.ko",
        "drivers/clk/qcom/gdsc-regulator.ko",
        "drivers/clk/qcom/gpucc-sm6150.ko",
        "drivers/clk/qcom/videocc-sm6150.ko",
        "drivers/cpufreq/qcom-cpufreq-hw.ko",
        "drivers/firmware/qcom-scm.ko",
        "drivers/hid/hid-uclogic-test.ko",
        "drivers/hwspinlock/qcom_hwspinlock.ko",
        "drivers/iio/test/iio-test-format.ko",
        "drivers/input/tests/input_test.ko",
        "drivers/interconnect/qcom/icc-bcm-voter.ko",
        "drivers/interconnect/qcom/icc-debug.ko",
        "drivers/interconnect/qcom/icc-rpmh.ko",
        "drivers/interconnect/qcom/qnoc-qos.ko",
        "drivers/interconnect/qcom/qnoc-sm6150.ko",
        "drivers/iommu/iommu-logger.ko",
        "drivers/irqchip/qcom-pdc.ko",
        "drivers/mailbox/msm_qmp.ko",
        "drivers/mailbox/qcom-apcs-ipc-mailbox.ko",
        "drivers/misc/open-dice.ko",
        "drivers/misc/vcpu_stall_detector.ko",
        "drivers/net/can/dev/can-dev.ko",
        "drivers/net/can/slcan/slcan.ko",
        "drivers/net/can/vcan.ko",
        "drivers/net/macsec.ko",
        "drivers/net/mii.ko",
        "drivers/net/ppp/bsd_comp.ko",
        "drivers/net/ppp/ppp_deflate.ko",
        "drivers/net/ppp/ppp_generic.ko",
        "drivers/net/ppp/ppp_mppe.ko",
        "drivers/net/ppp/pppox.ko",
        "drivers/net/ppp/pptp.ko",
        "drivers/net/slip/slhc.ko",
        "drivers/net/usb/aqc111.ko",
        "drivers/net/usb/asix.ko",
        "drivers/net/usb/ax88179_178a.ko",
        "drivers/net/usb/cdc_eem.ko",
        "drivers/net/usb/cdc_ether.ko",
        "drivers/net/usb/cdc_ncm.ko",
        "drivers/net/usb/r8152.ko",
        "drivers/net/usb/r8153_ecm.ko",
        "drivers/net/usb/rtl8150.ko",
        "drivers/net/usb/usbnet.ko",
        "drivers/net/wwan/wwan.ko",
        "drivers/nvmem/nvmem_qfprom.ko",
        "drivers/phy/qualcomm/phy-qcom-ufs.ko",
        "drivers/phy/qualcomm/phy-qcom-ufs-qmp-v3-660.ko",
        "drivers/pinctrl/qcom/pinctrl-msm.ko",
        "drivers/pinctrl/qcom/pinctrl-sm6150.ko",
        "drivers/pps/pps_core.ko",
        "drivers/ptp/ptp.ko",
        "drivers/ptp/ptp_kvm.ko",
        "drivers/regulator/proxy-consumer.ko",
        "drivers/regulator/rpmh-regulator.ko",
        "drivers/remoteproc/rproc_qcom_common.ko",
        "drivers/rpmsg/glink_pkt.ko",
        "drivers/rpmsg/qcom_glink.ko",
        "drivers/rpmsg/qcom_glink_slatecom.ko",
        "drivers/rpmsg/qcom_glink_smem.ko",
        "drivers/rtc/lib_test.ko",
        "drivers/scsi/sg.ko",
        "drivers/soc/qcom/boot_stats.ko",
        "drivers/soc/qcom/cmd-db.ko",
        "drivers/soc/qcom/eud.ko",
        "drivers/soc/qcom/llcc-qcom.ko",
        "drivers/soc/qcom/memory_dump_v2.ko",
        "drivers/soc/qcom/pdr_interface.ko",
        "drivers/soc/qcom/qcom_aoss.ko",
        "drivers/soc/qcom/qcom_ice.ko",
        "drivers/soc/qcom/qcom_rpmh.ko",
        "drivers/soc/qcom/qcom_soc_wdt.ko",
        "drivers/soc/qcom/qcom_wdt_core.ko",
        "drivers/soc/qcom/qmi_helpers.ko",
        "drivers/soc/qcom/qti_pmic_glink.ko",
        "drivers/soc/qcom/secure_buffer.ko",
        "drivers/soc/qcom/slatecom_spi.ko",
        "drivers/soc/qcom/smem.ko",
        "drivers/soc/qcom/smp2p.ko",
        "drivers/soc/qcom/socinfo.ko",
        "drivers/tty/serial/msm_geni_serial.ko",
        "drivers/ufs/host/ufs-qcom.ko",
        "drivers/uio/msm_sharedmem/msm_sharedmem.ko",
        "drivers/usb/class/cdc-acm.ko",
        "drivers/usb/mon/usbmon.ko",
        "drivers/usb/serial/ftdi_sio.ko",
        "drivers/usb/serial/usbserial.ko",
        "drivers/virtio/virtio_balloon.ko",
        "drivers/virtio/virtio_pci.ko",
        "drivers/virtio/virtio_pci_modern_dev.ko",
        "fs/ext4/ext4-inode-test.ko",
        "fs/fat/fat_test.ko",
        "kernel/kheaders.ko",
        "kernel/time/time_test.ko",
        "kernel/trace/qcom_ipc_logging.ko",
        "lib/crypto/libarc4.ko",
        "lib/kunit/kunit.ko",
        "lib/kunit/kunit-example-test.ko",
        "lib/kunit/kunit-test.ko",
        "mm/zsmalloc.ko",
        "net/6lowpan/6lowpan.ko",
        "net/6lowpan/nhc_dest.ko",
        "net/6lowpan/nhc_fragment.ko",
        "net/6lowpan/nhc_hop.ko",
        "net/6lowpan/nhc_ipv6.ko",
        "net/6lowpan/nhc_mobility.ko",
        "net/6lowpan/nhc_routing.ko",
        "net/6lowpan/nhc_udp.ko",
        "net/8021q/8021q.ko",
        "net/9p/9pnet.ko",
        "net/9p/9pnet_fd.ko",
        "net/bluetooth/bluetooth.ko",
        "net/bluetooth/hidp/hidp.ko",
        "net/bluetooth/rfcomm/rfcomm.ko",
        "net/can/can.ko",
        "net/can/can-bcm.ko",
        "net/can/can-gw.ko",
        "net/can/can-raw.ko",
        "net/core/dev_addr_lists_test.ko",
        "net/ieee802154/6lowpan/ieee802154_6lowpan.ko",
        "net/ieee802154/ieee802154.ko",
        "net/ieee802154/ieee802154_socket.ko",
        "net/l2tp/l2tp_core.ko",
        "net/l2tp/l2tp_ppp.ko",
        "net/mac802154/mac802154.ko",
        "net/nfc/nfc.ko",
        "net/qrtr/qrtr.ko",
        "net/qrtr/qrtr-smd.ko",
        "net/rfkill/rfkill.ko",
        "net/tipc/diag.ko",
        "net/tipc/tipc.ko",
        "net/vmw_vsock/vmw_vsock_virtio_transport.ko",
        "sound/soc/soc-topology-test.ko",
        "sound/soc/soc-utils-test.ko",
    ]

    _qcs610_debug_in_tree_modules = _qcs610_in_tree_modules + [
        # keep sorted
    ]

    for variant in le_variants:
        board_kernel_cmdline_extras = []
        if variant == "debug-defconfig":
            mod_list = _qcs610_debug_in_tree_modules
            board_kernel_cmdline_extras += [
                # do not sort
                "console=ttyMSM0,115200n8",
                "qcom_geni_serial.con_enabled=1",
                "earlycon",
                "ufshcd_core.uic_cmd_timeout=2000",
            ]
        else:
            mod_list = _qcs610_in_tree_modules

        define_msm_le(
            msm_target = target_name,
            variant = variant,
            defconfig = "build.config.msm.qcs610",
            in_tree_module_list = mod_list,
            boot_image_opts = boot_image_opts(
                board_kernel_cmdline_extras = board_kernel_cmdline_extras,
                boot_image_header_version = 2,
                base_address = 0x80000000,
                page_size = 4096,
            ),
        )
